### ISSUE TITLE
Cannot load file

### ISSUE THREAD

**Issue by grego1981** [DebugBill/glpi2mdt#3] opened 2017-09-28 06:04 UTC
Hello!
I've installed the plugin and set it up to work with my mdt server. The database connection is OK and some values are inserted in the GLPI DB but I get the error "Cannot load file /mnt/mdt/control/Applications.xml" which is a valid path for the www-data user and the following appears in the _log/php-errors.log. Also when trying the tab Auto install on any computer I get simply the Loading .... screen and nothing more. (GLPI 9.1.6)

2017-09-28 08:58:02 [@itsrv-05]
Undefined function PluginGlpi2mdtToolbox::croncheckUpdate (for cron)
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Warning(2): Declaration of PluginGlpi2mdtConfig::show() should be compatible with CommonGLPI::show($options = Array)
  Backtrace :
  plugins/glpi2mdt/inc/config.class.php:38
  inc/autoload.function.php:326                      include_once()
  :                                                  glpi_autoload()
  plugins/glpi2mdt/front/config.form.php:42          spl_autoload_call()
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Warning(2): Declaration of PluginGlpi2mdtCronTask::getTypeName() should be compatible with CommonGLPI::getTypeName($nb = 0)
  Backtrace :
  inc/autoload.function.php:326
  inc/autoload.function.php:326                      include_once()
  :                                                  glpi_autoload()
  plugins/glpi2mdt/front/config.form.php:62          spl_autoload_call()
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Deprecated function(8192): Non-static method PluginGlpi2mdtCronTask::cronUpdateBaseconfigFromMDT() should not be called statically
  Backtrace :
  plugins/glpi2mdt/front/config.form.php:62
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:131
  :                                                  PluginGlpi2mdtMdt->__destruct()
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:133
  :                                                  PluginGlpi2mdtMdt->__destruct()
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:131
  :                                                  PluginGlpi2mdtMdt->__destruct()
2017-09-28 08:58:50 [7@itsrv-05]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:133
  :                                                  PluginGlpi2mdtMdt->__destruct()

**Comment by grego1981** [comment] 2017-09-28 16:44
also error in cronlog blocking FusionInv checks:

Undefined function PluginGlpi2mdtToolbox::croncheckUpdate (for cron)

**Comment by DebugBill** [comment] 2017-09-29 07:12
Hi,
Sorry for the delay but I apparently missed the Github notice alerting me on your issue....

For your problem with accessing "Applications.xml" I suspect something related to SELinux. Are you using it? I had quite a hard time mounting the CIFS drive with proper SELinux rights. Here is the line I have in my system (CentOS 7):
//server.locall/DeploymentShare$/Control /var/www/html/glpi/mdt cifs uid=apache,forceuid,gid=apache,forcegid,context=system_u:object_r:httpd_
sys_rw_content_t:s0,ro,username=install,password=xxxxxxxxxxxxxxxxxx 0 0

Try disabling SELinux just in case....

For your other errors, which version are you using? The current one is 0.1.1 and it works fine for us with GLPI 9.1.6. Your traces remind me of issues I've corrected some time ago...

**Comment by grego1981** [comment] 2017-09-29 08:08
I will try your suggestions when the plugin will be available for 9.2, I had to updgrade today.. I use ubuntu 16.04, with app armor but I believe that the problem lies with the mounting on my part. I will investigate further and come back to you!

**Comment by DebugBill** [comment] 2017-09-29 11:22
You don't need to wait, up to my knowledge the plugin works fine with 9.2, but only my dev instance is upgraded, the production one is still 9.1.6 so I may not have seen all possible issues. Anyway, having one tester using 9.2 would be fine.

Have you enabled data reporting and new version checks? This also helps me in seing which configurations are the most common so I can direct my efforts in more sensible directions. At the moment only one user reports using 9.2 but he disabled all other information.

**Comment by grego1981** [comment] 2017-09-29 11:40
OK, I've installed it on my 9.2 installation and turned on Report usage data. I only got this error this time:

2017-09-29 14:33:33 [7@]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:131
  :                                                  PluginGlpi2mdtMdt->__destruct()
2017-09-29 14:33:33 [7@]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:133
  :                                                  PluginGlpi2mdtMdt->__destruct()


Also now the share is visible from the www-data user but still I get the
 Cannot load file /mnt/mdt/control/Applications.xml error. I don't know if it helps but I have a new MDT Installation and the Applications.xml file has only the header.


Thank you

**Comment by DebugBill** [comment] 2017-09-29 11:55
I think I see you. Are you in Greece?

The error message for Applications appears if "simple_xml_load_file" fails, so I suspect an almost empty fail may make it fail. My MDT instance was already populated when I started the project so there may be a bug when no application is defined. Can you try to create a fake one?

Also, there is a check in the code that is supposed to detect SELinux issues
      if (file_exists($dst) and !(is_readable($dst)) echo "Check access rights, and more specifically SELinux settings.</td></tr>";

Apparently you did not fire it but it may be worth trying this line in a test script. When the problem lies with SELinux, you can see the file, but can't open it. If you can open it read-only then the problem is somewhere else.

The error with DBModule is more surprising. This variable is initialized with the PHP module to be used to access the MS-SQL database, so it contains either "odbc" or "msql". It can't be empty as not having any of those modules would prevent you from enabling the plugin in the first place. Unless you have restored the database from another installation where the plugin was already enabled (never tested this though...)
Do you have either mssql or odbc module installed? I think mssql was deprecated in PHP 7 so it should be odbc only for you.

**Comment by grego1981** [comment] 2017-09-29 12:13
Yes, you can see me corectly, I use Ubuntu 16.04 as my server and there is no SELinux but apparmor instead which I cannot/don't know how to disable it without uninstalling  mysql as well. Though as the www-data user I can open save even move or rename the file, without problem. I will create something in mdt and see if that changes anything.

**Comment by grego1981** [comment] 2017-09-29 12:20
I have created an Application and now the output changes, I get another error:
Cannot load file Array['FileShare']/TaskSequences.xml

I believe that it doesn't like empty files because this one is empty too. I will create something and get back to you

**Comment by DebugBill** [comment] 2017-09-29 12:36
Looks like it..... Clearly I have to take into account empty files in my code :-)

It's is only those two, so you should be ok thereafter. 
Anyway, without at least one sequence task there is not much you can do with the plugin. As stated in my minimal documentation, you should alreadyhave a fully functionnal MDT installation before you cna do anything useful with the plugin.  
Applications are an option though, so this I must definitely take care of.

**Comment by grego1981** [comment] 2017-09-29 12:39
Confirmed, you have to have something configured for it to initialize properly.  Now another problem, I can see the setting in the computer auto installaion tab, I just cleared the date, and hit save and I get the following error in apache error.log 

[Fri Sep 29 15:36:14.163611 2017] [:error] [pid 1414] [client :49465] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PluginGlpi2mdtMdt::getMdtIds() must be an instance of Computer, string given, called in /var/www/html/glpi/plugins/glpi2mdt/inc/computer.class.php on line 159 and defined in /var/www/html/glpi/plugins/glpi2mdt/inc/mdt.class.php:270\nStack trace:\n#0 /var/www/html/glpi/plugins/glpi2mdt/inc/computer.class.php(159): PluginGlpi2mdtMdt->getMdtIds('321')\n#1 /var/www/html/glpi/plugins/glpi2mdt/front/computer.form.php(46): PluginGlpi2mdtComputer->updateMDT('321')\n#2 {main}\n  thrown in /var/www/html/glpi/plugins/glpi2mdt/inc/mdt.class.php on line 270, referer: http://host/glpi/front/computer.form.php?id=321

**Comment by DebugBill** [comment] 2017-09-29 15:49
I'm afraid I can't reproduce it. I suspect it only fires with PHP 7. I can see in your log that you are passing string '321' to function getMDTIds which is OK according to my code but wrong according to the function declaration (I've been inconsistent here). PHP 5.6 does not complain..... 

I needs some time to review the code and hopefully fix this. Stay tuned.

**Comment by DebugBill** [comment] 2017-09-29 21:18
Until I release a new version fixing the bugs you've found (thanks by the way), can you try this fix: 
in file glpi2mdt/inc/mdt.class.php, line 270
function getMdtIds(computer $id) {

remove the type "computer". This is really a mistake but PHP 5.5 and 5.6 don't seem to care much about variable typing.

**Comment by grego1981** [comment] 2017-09-29 21:54
It seems to work ok, the error stopped but it takes some time to save settings. Also in php-errors.log I get 


2017-09-30 00:50:25 [7@i
]
  *** PHP Notice(8): Undefined variable: DBModule
  Backtrace :
  plugins/glpi2mdt/inc/mdt.class.php:133
  inc/commonglpi.class.php:483                       PluginGlpi2mdtMdt->__destruct()
  ajax/common.tabs.php:96                            CommonGLPI::displayStandardTab()
root@:~#

**Comment by DebugBill** [comment] 2017-09-30 07:42
I found the cause for this one. it had no consequence at all, it was just not closing some DB links when destroying the class, but PHP would take care of it anyway a few milliseconds later. Fix is commited on github.

I'm surprised about the delay. On my system I don't see any difference with or without the plugin enabled. It must be waiting for something somewhere. Is the data properly written in your DMT database?

Do you have a large database? Either on GLPI or MDT? We only have about 2000 computers, this could make a difference.

**Comment by grego1981** [comment] 2017-09-30 07:59
I've just updated, The error is no more, the speed is at it's normal. My net is significaly smaller (230 clients) . Everything seems OK, I have something new in the logs maybe it's nothing but it may help you in the future (I believe some of it comes from the newer version of php i use 7.0):

2017-09-30 10:56:01 [@]
  *** PHP Warning(2): Declaration of PluginGlpi2mdtCronTask::getTypeName() should be compatible wi                                                                                                         th CommonGLPI::getTypeName($nb = 0)
  Backtrace :
  plugins/glpi2mdt/inc/crontask.class.php:43
  inc/autoload.function.php:347                      include_once()
  :                                                  glpi_autoload()
  :                                                  spl_autoload_call()
  inc/crontask.class.php:823                         is_callable()
  front/cron.php:87                                  CronTask::launch()
2017-09-30 10:56:01 [@]
  *** PHP Deprecated function(8192): Non-static method PluginGlpi2mdtCronTask::cronExpireOSInstall                                                                                                         Flag() should not be called statically
  Backtrace :
  inc/crontask.class.php:832
  front/cron.php:87                                  CronTask::launch()

**Closed** 2017-10-03 20:15 UTC

**Comment by DebugBill** [comment] 2017-10-03 20:40
Version 0.1.2 is out. Thanks for your feedback on PHP 7. This one will accept empty MDT databases.
